---
name: "Publish ðŸ“¦ to Test PyPI"
on:
  workflow_run:
    workflows:
      - "PyTest ðŸ"
    types:
      - completed
jobs:
  Run-Tests:
    name: Publish to Test PyPI
    runs-on: ubuntu-20.04
    environment: PyPI Environment
    steps:
      - name: Checkout the main branch
        uses: actions/checkout@v2

      - name: Setup Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          architecture: 'x64'

      - name: Install pypa/build
        run: >-
          python -m pip install
          build --user

      - name: Build a binary wheel and a source tarball
        run: >-
          python -m
          build
          --sdist
          --wheel
          --outdir dist/

      - name: Publish distribution ðŸ“¦ to Test PyPI
        uses: pypa/gh-action-pypi-publish@v1.5.0
        with:
          user: __token__
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/